/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_eki_marshalexp_memshell_MTomcatJNIFilter */

#ifndef _Included_xyz_eki_marshalexp_memshell_MTomcatJNIFilter
#define _Included_xyz_eki_marshalexp_memshell_MTomcatJNIFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_eki_marshalexp_memshell_MTomcatJNIFilter
 * Method:    doExec
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_eki_marshalexp_memshell_MTomcatJNIFilter_doExec
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
